SET STATISTICS TIME ON
PRINT 'STRING_AGG PART'
SELECT STRING_AGG(CAST(VCH_NO AS nvarchar(MAX)),', ')
FROM GLTRAN_DETL

PRINT '-------------------------------------'
PRINT 'STUFF PART'
SELECT STUFF((SELECT CONCAT(', ',VCH_NO) FROM GLTRAN_DETL FOR XML PATH('')),1,2,'')

SELECT COUNT(1) FROM CUSTOMER_MAST