USE [INFINITY_032_002]
GO

PRINT 'Index Creation Started'+CONVERT(VARCHAR(50),GETDATE(),113)
GO

CREATE NONCLUSTERED INDEX [INDEX1] ON [dbo].[GLTRAN_DETL_NEW]
(
	[BR_CODE] ASC,
	[VALUE_DATE] ASC,
	[GL_CODE] ASC
)
INCLUDE([AC_NO],[AMT]) WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PS_YEARLY_TRANSACTIONS]([VALUE_DATE])
GO

PRINT 'Created Index 1 On GLTRAN_DETL_NEW '+CONVERT(VARCHAR(50),GETDATE(),113)
GO

CREATE NONCLUSTERED INDEX [INDEX2] ON [dbo].[GLTRAN_DETL_NEW]
(
	[VCH_NO] ASC,
	[BR_CODE] ASC,
	[GL_CODE] ASC,
	[AC_NO] ASC
)
INCLUDE([AMT],[DESC1],[TRAN_ID],[VALUE_DATE]) WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PS_YEARLY_TRANSACTIONS]([VALUE_DATE])
GO

PRINT 'Created Index 2 On GLTRAN_DETL_NEW '+CONVERT(VARCHAR(50),GETDATE(),113)
GO

CREATE NONCLUSTERED INDEX [INDEX3] ON [dbo].[GLTRAN_DETL_NEW]
(
	[AC_NO] ASC,
	[GL_CODE] ASC,
	[BR_CODE] ASC,
	[VALUE_DATE] ASC
)
INCLUDE([AMT],[VCH_NO]) WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PS_YEARLY_TRANSACTIONS]([VALUE_DATE])
GO

PRINT 'Created Index 3 On GLTRAN_DETL_NEW '+CONVERT(VARCHAR(50),GETDATE(),113)
GO

CREATE CLUSTERED COLUMNSTORE INDEX [PK_CCI_GLTRAN_DETL] 
ON [dbo].[GLTRAN_DETL_NEW] 
WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0, DATA_COMPRESSION = COLUMNSTORE) 
ON [PS_YEARLY_TRANSACTIONS]([VALUE_DATE])
GO

PRINT 'Created PK_CCI Index On GLTRAN_DETL_NEW '+CONVERT(VARCHAR(50),GETDATE(),113)