USE [MASTER]
GO

CREATE OR ALTER   PROCEDURE [DBO].[USP_DEFRAGDB_BATCH]
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @DBNAME VARCHAR(100)='';
	DECLARE @STATUS VARCHAR(100)='';
	SELECT NAME DATABASENAME INTO #DBLIST FROM MASTER.DBO.SYSDATABASES WHERE [NAME] LIKE 'INFINITY%';
	RETRY:
	BEGIN TRY
		WHILE EXISTS(SELECT 1 FROM #DBLIST)
		BEGIN
			SET @DBNAME='';
			SELECT TOP 1 @DBNAME=DATABASENAME FROM #DBLIST ORDER BY DATABASENAME ASC;
			IF LEN(@DBNAME)>0
			BEGIN
				SET @STATUS='PROCESSING ON :'+@DBNAME;
				INSERT INTO DEFRAGDBBATCH_LOG(LOGTYPE,EXECDATETIME,DATABASENAME,ERRORMESSAGE,ERRORSEVERITY,ERRORSTATE) VALUES('START',GETDATE()   ,@DBNAME     ,NULL,NULL,NULL);
				EXEC('EXEC '+@DBNAME+'.DBO.USP_DEFRAG_DB');
			END
			DELETE FROM #DBLIST WHERE DATABASENAME=@DBNAME;
		END
	END TRY
	BEGIN CATCH
		DELETE FROM #DBLIST WHERE DATABASENAME=@DBNAME
		DECLARE @ERRORSEVERITY INT = ERROR_SEVERITY();
		DECLARE @ERRORSTATE INT = ERROR_STATE();
		DECLARE @ERRORMESSAGE VARCHAR(MAX)=ERROR_MESSAGE();
		INSERT INTO DEFRAGDBBATCH_LOG(LOGTYPE,EXECDATETIME,DATABASENAME,ERRORMESSAGE,ERRORSEVERITY,ERRORSTATE) VALUES('ERROR',GETDATE(),@DBNAME,@ERRORMESSAGE,@ERRORSEVERITY,@ERRORSTATE);
		GOTO RETRY;
	END CATCH  	
END


