USE [MASTER]
GO

DROP TABLE IF EXISTS UPDATESTATS_LOG
CREATE TABLE [DBO].[UPDATESTATS_LOG](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[LOGTYPE] [VARCHAR](20) NOT NULL,
	[STATUS] [VARCHAR](20) NULL,
	[START_DATETIME] [DATETIME] NOT NULL,
	[END_DATETIME] [DATETIME] NOT NULL,
	[DIFF_SECS] AS (DATEDIFF(s,START_DATETIME,END_DATETIME)) PERSISTED,
	[DATABASENAME] [VARCHAR](100) NOT NULL,
	[ERRORMESSAGE] [VARCHAR](MAX) NULL,
	[ERRORSEVERITY] [INT] NULL,
	[ERRORSTATE] [INT] NULL,
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SELECT DATEDIFF(s,'2023-04-14 10:01:00','2023-04-14 10:02:00')