USE [MASTER]
GO

CREATE OR ALTER   PROCEDURE [DBO].[USP_UPDATESTATS_BATCH]
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @DBNAME VARCHAR(100)='';
	DECLARE @STATUS VARCHAR(100)='';
	DECLARE @TIME DATETIME;
	SELECT NAME DATABASENAME 
	INTO #DBLIST 
	FROM MASTER.DBO.SYSDATABASES WHERE [NAME] LIKE 'INFINITY%';
	RETRY:
	BEGIN TRY
		WHILE EXISTS(SELECT 1 FROM #DBLIST)
		BEGIN
			SET @DBNAME='';
			SET @TIME = GETDATE();
			SELECT TOP 1 @DBNAME=DATABASENAME FROM #DBLIST ORDER BY DATABASENAME ASC;
			IF LEN(@DBNAME)>0
			BEGIN
				SET @STATUS='PROCESSING ON :'+@DBNAME;
				--SELECT @STATUS
				INSERT INTO UPDATESTATS_LOG(LOGTYPE,START_DATETIME,DATABASENAME,ERRORMESSAGE,ERRORSEVERITY,ERRORSTATE,END_DATETIME) 
				VALUES('START',@TIME   ,@DBNAME     ,NULL,NULL,NULL,@TIME);
				
				EXEC('EXEC '+@DBNAME+'.DBO.SP_UPDATESTATS');
				
				UPDATE UPDATESTATS_LOG SET [STATUS] ='COMPLETED',END_DATETIME = GETDATE() WHERE DATABASENAME = @DBNAME AND START_DATETIME = @TIME
			END
			DELETE FROM #DBLIST WHERE DATABASENAME=@DBNAME;
		END
	END TRY
	BEGIN CATCH
		DELETE FROM #DBLIST WHERE DATABASENAME=@DBNAME
		DECLARE @ERRORSEVERITY INT = ERROR_SEVERITY();
		DECLARE @ERRORSTATE INT = ERROR_STATE();
		DECLARE @ERRORMESSAGE VARCHAR(MAX)=ERROR_MESSAGE();
		INSERT INTO UPDATESTATS_LOG(LOGTYPE,START_DATETIME,DATABASENAME,ERRORMESSAGE,ERRORSEVERITY,ERRORSTATE) 
		VALUES('ERROR',GETDATE(),@DBNAME,@ERRORMESSAGE,@ERRORSEVERITY,@ERRORSTATE);
		GOTO RETRY;
	END CATCH  	
END
GO

--EXEC USP_UPDATESTATS_BATCH

--SELECT * FROM UPDATESTATS_LOG WITH(NOLOCK)