DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_NEWS_AND_EVENTS';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_NEWS_AND_EVENTS' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_NEWS_AND_EVENTS'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_NEWS_AND_EVENTS_CATEGORY';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_NEWS_AND_EVENTS_CATEGORY' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_NEWS_AND_EVENTS_CATEGORY'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_GLOBAL_TRAN_LIMIT';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_GLOBAL_TRAN_LIMIT' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_GLOBAL_TRAN_LIMIT'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_SCOPE_NAMED_GL';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_SCOPE_NAMED_GL' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_SERVICE_SCOPE_NAMED_GL'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_NAMED_GL_GL_CODE_DETL';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_NAMED_GL_GL_CODE_DETL' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_NAMED_GL_GL_CODE_DETL'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_NAMED_GL_GL_CODE_MAST';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_NAMED_GL_GL_CODE_MAST' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_NAMED_GL_GL_CODE_MAST'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_OPTION_TRAN_LIMIT_DETL';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_OPTION_TRAN_LIMIT_DETL' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_SERVICE_OPTION_TRAN_LIMIT_DETL'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_OPTION_TRAN_LIMIT_MAST';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_OPTION_TRAN_LIMIT_MAST' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_SERVICE_OPTION_TRAN_LIMIT_MAST'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_NAMED_GL';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_NAMED_GL' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_NAMED_GL'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_OPTIONS';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_OPTIONS' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_SERVICE_OPTIONS'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_PROVIDER';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_PROVIDER' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_SERVICE_PROVIDER'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_SCOPE_TRAN_LIMIT_DETL';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_SCOPE_TRAN_LIMIT_DETL' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_SERVICE_SCOPE_TRAN_LIMIT_DETL'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_SCOPE_TRAN_LIMIT_MAST';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_SERVICE_SCOPE_TRAN_LIMIT_MAST' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_SERVICE_SCOPE_TRAN_LIMIT_MAST'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='AD_AGENCY';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='AD_AGENCY' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='AD_AGENCY'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_ADVERTISEMENT';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_ADVERTISEMENT' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_ADVERTISEMENT'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_ADVERTISEMENT_CATEGORY';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_ADVERTISEMENT_CATEGORY' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_ADVERTISEMENT_CATEGORY'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_ADVERTISEMENT_QUOTA';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_ADVERTISEMENT_QUOTA' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_ADVERTISEMENT_QUOTA'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_ADVERTISEMENT_CUSTOMER_READ_LOG';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_ADVERTISEMENT_CUSTOMER_READ_LOG' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_ADVERTISEMENT_CUSTOMER_READ_LOG'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_MESSAGE_READ_LOG';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_MESSAGE_READ_LOG' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_MESSAGE_READ_LOG'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_MESSAGE_TO_CUSTOMER_AT_LOGIN_READ_LOG';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_MESSAGE_TO_CUSTOMER_AT_LOGIN_READ_LOG' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_MESSAGE_TO_CUSTOMER_AT_LOGIN_READ_LOG'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_MESSAGE_TO_CUSTOMERS_AT_LOGIN';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_MESSAGE_TO_CUSTOMERS_AT_LOGIN' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_MESSAGE_TO_CUSTOMERS_AT_LOGIN'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_PAYMENT_CASHBACK_DETL';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_PAYMENT_CASHBACK_DETL' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_PAYMENT_CASHBACK_DETL'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_PAYMENT_CASHBACK_MAST';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_PAYMENT_CASHBACK_MAST' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_PAYMENT_CASHBACK_MAST'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_TRAN';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='DFS_TRAN' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='DFS_TRAN'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_AGENT_TRAN_REQUEST';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_AGENT_TRAN_REQUEST' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_AGENT_TRAN_REQUEST'

DELETE MF FROM INDEX_MAIN_FIELDS MF INNER JOIN INDEX_DETL D ON D.IDX_ID=MF.IDX_ID  INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_PAYMENT_TRAN';
DELETE D FROM INDEX_DETL D INNER JOIN INDEX_MAST M ON M.TBL_ID=D.TBL_ID AND M.TABLE_NAME='MOBILE_PAYMENT_TRAN' 
DELETE FROM INDEX_MAST WHERE TABLE_NAME='MOBILE_PAYMENT_TRAN'